//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa.NET.Annotations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alexa.NET.Annotations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill methods must have a return type of either SkillResponse or Task&lt;SkillResponse&gt;..
        /// </summary>
        internal static string InvalidHandlerReturnTypeDescription {
            get {
                return ResourceManager.GetString("InvalidHandlerReturnTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} is not returning a SkillResponse object.
        /// </summary>
        internal static string InvalidHandlerReturnTypeMessageFormat {
            get {
                return ResourceManager.GetString("InvalidHandlerReturnTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid return type.
        /// </summary>
        internal static string InvalidHandlerReturnTypeTitle {
            get {
                return ResourceManager.GetString("InvalidHandlerReturnTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill methods using BeforeRequest or BeforeResponse must have a return type of either void, Task, SkillResponse or Task&lt;SkillResponse&gt;..
        /// </summary>
        internal static string InvalidInterceptorReturnTypeDescription {
            get {
                return ResourceManager.GetString("InvalidInterceptorReturnTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} does not have a void, Task or SkillResponse return type.
        /// </summary>
        internal static string InvalidInterceptorReturnTypeMessageFormat {
            get {
                return ResourceManager.GetString("InvalidInterceptorReturnTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid return type.
        /// </summary>
        internal static string InvalidInterceptorReturnTypeTitle {
            get {
                return ResourceManager.GetString("InvalidInterceptorReturnTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill methods can only use supported types as parameters..
        /// </summary>
        internal static string InvalidParameterDescription {
            get {
                return ResourceManager.GetString("InvalidParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type {0} in method {1} is not recognised.
        /// </summary>
        internal static string InvalidParameterMessageFormat {
            get {
                return ResourceManager.GetString("InvalidParameterMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter in method signature.
        /// </summary>
        internal static string InvalidParameterTitle {
            get {
                return ResourceManager.GetString("InvalidParameterTitle", resourceCulture);
            }
        }
    }
}
